Hi guys,<br>
Welcome back to the pandas essentials, in this lecture we are going to talk about
# Groupby

Groupby is one of the most important and key functionality in pandas. It allows us to group data together, call aggregate functions and combinethe result in three steps split-apply-combine:<br>
Before we move on the hands-in, let's try to understand how the split-apply-combine work, using a data in different ccolours!

* <code><b>split:</b></code> In this process data contained in a pandas object (e.g. Series, DataFrame) is split into groups based on one or more keys that we provide. The splitting is performed on a particular axis of an object. For example, a data frame can be grouped on its row (axis=0) or its column (axis=1).
* <code><b>apply:</b></code> Once splitting is done the function is applied to all groups independently, producing a new value.
* <code><b>combine:</b></code> Finally, the result of all those functions applications are combined into a resultant object. The form of the resulting object will usually depend on what's being done to the data.<br>

Let's explore with some examples.

In [ ]:
import pandas as pd

Let's create a dictionary and convert that into pandas dataframe

In [ ]:
data = {'Store' : ['Walmart','Walmart','Costco','Costco','Target','Target'],
        'Customer' : ['Tim','Jermy','Mark','Denice','Ray','Sam'],
        'Sales' : [150, 200, 550, 90, 430, 120]}
df = pd.DataFrame(data)
df

     Store Customer  Sales
0  Walmart      Tim    150
1  Walmart    Jermy    200
2   Costco     Mark    550
3   Costco   Denice     90
4   Target      Ray    430
5   Target      Sam    120

In this dataframe, we have a Customer unique name, Sales in number and store name.<br>
Let's group the data, in df, based on column 'Store' using groupby method. This will create a DataFrameGroupBy object.

Grab the df, access the groupby method "" and pass the column we want to group the data on.<br>
Notice, we get a groupby object, stored in a memory 0x....

In [ ]:
df.groupby('Store')[['Sales']].sum()

         Sales
Store
Costco     640
Target     550
Walmart    350

In [ ]:
df.groupby('Store')[['Sales','Customer']].count()

         Sales  Customer
Store
Costco       2         2
Target       2         2
Walmart      2         2

Let's save the created object as new variable.

In [ ]:
by_store = df.groupby("Store")

In [ ]:
by_store