In [1]:
#pandas import করা
import pandas as pd

In [2]:
#ডেটা লোড করা
df = pd.read_csv('/content/City_of_Chicago_Payroll_Data.csv')

In [3]:
#Dataset shape,info check
df.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,"$107,790.00",NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,"$104,628.00",NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,"$114,324.00",NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,"$76,932.00",NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,"$111,474.00",NaN

In [4]:
df.shape

(32658, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
dtypes: float64(1), object(7)
memory usage: 2.0+ MB

In [9]:
#ক্লিন করা
df['Annual Salary']=df['Annual Salary'].astype(str).str.replace(r'[$,]','',regex=True).replace('nan',None).astype(float)

In [10]:
df['Annual Salary']

0        107790.0
1        104628.0
2        114324.0
3         76932.0
4        111474.0
           ...
32653     90024.0
32654     48078.0
32655     87006.0
32656     93354.0
32657    115932.0
Name: Annual Salary, Length: 32658, dtype: float64

In [11]:
df['Hourly Rate']=df['Hourly Rate'].astype(str).str.replace(r'[$,]','',regex=True).replace('nan',None).astype(float)

In [12]:
df['Hourly Rate']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
32653   NaN
32654   NaN
32655   NaN
32656   NaN
32657   NaN
Name: Hourly Rate, Length: 32658, dtype: float64

In [13]:
df.isnull().sum()

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        24775
Annual Salary         7883
Hourly Rate          24775
dtype: int64

In [14]:
# Median দিয়ে fill করা
df['Annual Salary'].fillna(df['Annual Salary'].median(), inplace=True)
df['Hourly Rate'].fillna(df['Hourly Rate'].median(), inplace=True)
df['Typical Hours'].fillna(df['Typical Hours'].median(), inplace=True)

/tmp/ipython-input-1103130053.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Annual Salary'].fillna(df['Annual Salary'].median(), inplace=True)
/tmp/ipython-input-1103130053.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Typical Hours'].fillna(df['Typical Hours'].median(), inplace=True)

In [15]:
df.isnull().sum()

Name                 0
Job Titles           0
Department           0
Full or Part-Time    0
Salary or Hourly     0
Typical Hours        0
Annual Salary        0
Hourly Rate          0
dtype: int64

In [16]:
df.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,40.0,107790.0,35.6
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,40.0,104628.0,35.6
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,40.0,114324.0,35.6
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,40.0,76932.0,35.6
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,40.0,111474.0,35.6

In [17]:
#Full-time vs Part-time analysis
print(df['Full or Part-Time'].value_counts())

Full or Part-Time
F    30676
P     1982
Name: count, dtype: int64

In [18]:
#Salary distribution
df['Annual Salary'].describe(include='all') #📌 Pandas দিয়ে Salary Distribution বোঝার উপায়

count     32658.000000
mean      88118.939386
std       17942.872535
min           0.960000
25%       84054.000000
50%       90024.000000
75%       93354.000000
max      300000.000000
Name: Annual Salary, dtype: float64

In [19]:
df['Annual Salary'].nunique()  #👉 কয় ধরনের ভিন্ন salary আছে

1038

In [21]:
df['Annual Salary'].value_counts().head(10) #👉 কোন বেতনটা সবচেয়ে বেশি জন পাচ্ছে, তার সংখ্যা

Annual Salary
90024.0     10251
87006.0      2252
93354.0      1390
84054.0       765
80016.0       754
96060.0       677
72510.0       645
48078.0       604
100980.0      477
92274.0       474
Name: count, dtype: int64

In [22]:
df['Annual Salary'].max() - df['Annual Salary'].min()  #👉 সর্বোচ্চ আর সর্বনিম্ন বেতনের পার্থক্য

299999.04

In [23]:
df['Annual Salary'].quantile([0.25, 0.5, 0.75, 0.9, 0.95])

0.25     84054.0
0.50     90024.0
0.75     93354.0
0.90    105804.0
0.95    114846.0
Name: Annual Salary, dtype: float64

In [24]:
pd.cut(df['Annual Salary'], bins=5).value_counts() #👉 এখানে বেতনের ডেটা 5 ভাগে ভাগ করবে (range বানাবে) এবং প্রতিটি range-এ কয়জন আছে তা দেখাবে।

Annual Salary
(60000.768, 120000.576]     28730
(-299.039, 60000.768]        2676
(120000.576, 180000.384]     1230
(180000.384, 240000.192]       20
(240000.192, 300000.0]          2
Name: count, dtype: int64

In [25]:
#Department Analysis
dept_count = df['Department'].value_counts().head(10)
dept_avg_salary = df.groupby('Department')['Annual Salary'].mean().sort_values(ascending=False).head(10)
dept_avg_hourly = df.groupby('Department')['Hourly Rate'].mean().sort_values(ascending=False).head(10)

In [26]:
dept_avg_salary

Department
DoIT               99681.029703
BUILDINGS          98864.833534
COPA               98784.705882
FIRE               97759.124350
MAYOR'S OFFICE     95659.740706
BOARD OF ETHICS    94552.500000
IPRA               94429.285714
BUDGET & MGMT      93836.727273
HUMAN RELATIONS    93778.588235
TRANSPORTN         90007.088704
Name: Annual Salary, dtype: float64

In [27]:
dept_avg_hourly

Department
WATER MGMNT          40.644585
GENERAL SERVICES     40.323992
TRANSPORTN           39.222756
HEALTH               35.913469
FIRE                 35.601917
LICENSE APPL COMM    35.600000
BOARD OF ELECTION    35.600000
ADMIN HEARNG         35.600000
INSPECTOR GEN        35.600000
BUILDINGS            35.600000
Name: Hourly Rate, dtype: float64

In [28]:
#Job Titles Analysis
job_titles = df['Job Titles'].value_counts().head(10)

In [29]:
job_titles

Job Titles
POLICE OFFICER                            9393
FIREFIGHTER-EMT                           1424
SERGEANT                                  1118
POOL MOTOR TRUCK DRIVER                    996
POLICE OFFICER (ASSIGNED AS DETECTIVE)     845
MOTOR TRUCK DRIVER                         728
SANITATION LABORER                         658
FIREFIGHTER                                564
CROSSING GUARD                             482
CONSTRUCTION LABORER                       464
Name: count, dtype: int64

In [30]:
df['Job Titles'].describe()

count              32658
unique              1095
top       POLICE OFFICER
freq                9393
Name: Job Titles, dtype: object